apiVersion: v1
kind: Service
metadata:
  name: arvmldevopspipeline-svc
  namespace: arvmldevopspipeline
spec:
  type: ClusterIP
  selector:
    app: arvmldevopspipeline
  ports:
    - name: http
      port: 8000
      targetPort: 8000
